name: first_app
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.4.1 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  concentric_transition: ^1.0.3 # Updated version
  country_code_picker: ^3.0.0 # Add this line
  cupertino_icons: ^1.0.6
  device_preview: ^1.2.0
  font_awesome_flutter: ^9.2.0
  pin_code_fields: ^8.0.0
  carousel_slider: ^5.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_signin_button: ^2.0.0
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/

  # Uncomment and adjust the following section to add custom fonts to your application.
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
